rm ./r/rmorris1218/ipify.json
rm ./r/repaygithub/dmsnitch.json
rm ./r/Richard-Barrett/providertemplate.json
rm ./r/Rob4t/google.json
rm ./r/rakutentech/vsphere.json
rm ./r/rfiestas/tumblr.json
rm ./r/ravitejb/vault.json
rm ./r/rh01/kubevirt-2.json
rm ./u/ugns/bref-orig.json
rm ./u/USFoods/newrelic.json
rm ./u/usfdmiller/newrelic.json
rm ./i/igor-feoktistov/flexbot.json
rm ./i/innovationnorway-archive/netbox-archived.json
rm ./i/innovationnorway-archive/seq-archived.json
rm ./i/innovationnorway-archive/databricks-archived-itp.json
rm ./i/innovarelabs/circleci.json
rm ./i/immuta/kubernetes.json
rm ./i/instaclustr/instaclustr.json
rm ./i/ibm-vpc-official/ibm.json
rm ./n/naushadh/keycloak.json
rm ./n/NicholasTing/contentful-legacy.json
rm ./n/nazarewk/external.json
rm ./n/nextgenhealthcare/sumologic.json
rm ./n/nextgenhealthcare/cloudhealth.json
rm ./g/geekmuse/sendmail.json
rm ./g/glindstedt/netbox.json
rm ./g/github-1729-rm/custom-unleash-philips.json
rm ./g/greut/kong.json
rm ./g/greut/consulacl.json
rm ./g/greut/consul.json
rm ./g/gregone/almost.json
rm ./6/6RiverSystems/kubernetes.json
rm ./z/zhoue341/aws.json
rm ./1/1819Project/snowflake.json
rm ./t/taoufik07/gandi.json
rm ./t/terraform-registry-test-org/nohookprivs.json
rm ./t/thomasmeeus/httpdownload.json
rm ./t/tkeber/auth0.json
rm ./t/tamu-edu/kion.json
rm ./t/twcc/twcc.json
rm ./t/Topolytics/gsuite.json
rm ./t/tomaspinho/gsuite.json
rm ./t/track-and-trace/ksql.json
rm ./t/terraform-registry-test-user/no-release-assets.json
rm ./t/terraform-registry-test-user/bad-manifest.json
rm ./t/trvon/openvswitch.json
rm ./s/stefansundin/ssh.json
rm ./s/SquadcastHub/squadcast-deprecated.json
rm ./s/sandhose/harbor.json
rm ./s/stephanebruckert/pagerduty.json
rm ./s/summittech-ca/esxi.json
rm ./s/so0k/filesystem.json
rm ./s/seuf/kubeportforward.json
rm ./s/seiji/feedly.json
rm ./s/smartfire-company/nexus.json
rm ./s/STollenaar/unit-converter.json
rm ./s/shakenfist/shakenfist.json
rm ./s/smehboub/incapsula.json
rm ./s/safanaj/archive.json
rm ./s/sl1pm4t/tfstate.json
rm ./s/sl1pm4t/kubernetes.json
rm ./s/samanthaq/circleci.json
rm ./s/sinsoku/esa.json
rm ./s/sikalabs/secret.json
rm ./s/sam-dumont/rabbitmq.json
rm ./a/atwatanmalikm/jenkins-forked.json
rm ./a/astha-jain/ibm.json
rm ./a/aman-ahuja-fortanix/oci.json
rm ./a/abdelazizhd/imgix.json
rm ./a/Azure/azapi.json
rm ./a/alejandrojnm/civo.json
rm ./a/anubhavmishra/jira.json
rm ./a/arjunrajnetapp/instaclustr.json
rm ./a/afdezl/helm.json
rm ./a/akshaykarle/mongodbatlas.json
rm ./a/AppViewX/appviewx-backup.json
rm ./a/aaronfeng/aws.json
rm ./a/agarciamiravet/azuredevops.json
rm ./a/avioconsulting/muleb2b.json
rm ./a/aperigault/postgresql.json
rm ./f/findkim/truncatedocs.json
rm ./f/findkim/vault.json
rm ./f/findkim/aws.json
rm ./f/findkim/legacydocs.json
rm ./f/form3tech-oss/vault.json
rm ./f/form3tech-oss/postgresreplication.json
rm ./f/form3tech-oss/githubdeploymentenvironment.json
rm ./f/form3tech-oss/auth0.json
rm ./f/form3tech-oss/form3.json
rm ./f/form3tech-oss/codeowners.json
rm ./f/form3tech-oss/alienvault.json
rm ./f/form3tech-oss/githubfile.json
rm ./f/FundingCircle/synthetics.json
rm ./f/FindHotel/sql.json
rm ./f/fcosta-td/cassandra.json
rm ./f/fourplusone/git.json
rm ./f/FormidableLabs/serverless.json
rm ./h/heph/pingdom.json
rm ./h/hyphengroup/kops.json
rm ./h/hgontijo/shell.json
rm ./h/hugomcfonseca/openfaas.json
rm ./h/hyperonecom/hyperone.json
rm ./m/migara/panos.json
rm ./m/mariussturm/okta.json
rm ./m/MerlinDMC/ldap.json
rm ./m/mesosphere/dcos.json
rm ./m/mikhail-anfimau/azuread.json
rm ./m/manifoldco/manifold.json
rm ./j/joshpmcghee/destroy.json
rm ./j/jtsaito/trello.json
rm ./j/jbunting/custom.json
rm ./j/julian3xl/appstream.json
rm ./j/jerakia/jerakia.json
rm ./j/justincampbell/almost.json
rm ./j/jgensler8/minikube.json
rm ./c/Cardfree/teamcity.json
rm ./c/covertbyte/jsonnext.json
rm ./c/chanzuckerberg/kubernetes.json
rm ./c/chanzuckerberg/datadog.json
rm ./c/cloudfoundry/csbpg.json
rm ./c/cloudfoundry/csbmysql.json
rm ./c/cloudfoundry/csbsqlserver.json
rm ./c/captn3m0/docker.json
rm ./c/c445/openstack.json
rm ./c/criteo-forks/azurerm.json
rm ./c/caryyu/kong.json
rm ./c/cloudposse/nexus.json
rm ./c/chaurasia-namrata/zoomapp.json
rm ./c/claranet/gitlab.json
rm ./c/claranet/ansiblevault.json
rm ./c/claranet/azuredevops.json
rm ./c/claranet/clouddeploy.json
rm ./c/crabmusket/restapi.json
rm ./c/cegeka/tss.json
rm ./c/cegeka/httpdownload.json
rm ./c/coveord/spinnaker.json
rm ./d/DanielMabbett/confluent.json
rm ./d/ddkclaudio/roztta-go.json
rm ./d/dpiddock/elasticsearch.json
rm ./d/devlucasc/databricks.json
rm ./d/disaac/logentries.json
rm ./d/dahendel/awx2.json
rm ./d/dikhan/openapi.json
rm ./d/denniswebb/splunk.json
rm ./d/dnna/twilio.json
rm ./d/dsa0x/nimbus.json
rm ./d/dsa0x/bad-manifest.json
rm ./v/Vanilla-s-Lab/transfer-sh.json
rm ./v/vancluever/acme-old.json
rm ./x/xaptum/xaptum.json
rm ./e/ernesgonzalez33/rhcs-rhtap.json
rm ./e/EvilSuperstars/get.json
rm ./e/EvilSuperstars/jsondecode.json
rm ./e/EvilSuperstars/jsonyaml.json
rm ./e/EvilSuperstars/jmespath.json
rm ./e/enriquebelarte/rhcs-rhtap.json
rm ./e/elblivion/librato.json
rm ./e/EliiseS/azuredevops-ms.json
rm ./e/ewilde/runscope.json
rm ./e/ewilde/openfaas.json
rm ./e/EBSCOIS/infoblox.json
rm ./e/esqp/freeipa.json
rm ./e/elifish4/cf.json
rm ./b/bjoernHeneka/kong.json
rm ./b/bdwyertech/aws.json
rm ./b/bgcorreia/hashicups.json
rm ./b/bigcommerce/cortex-old.json
rm ./b/babbel/rollbar.json
rm ./b/babbel/codeclimate.json
rm ./b/babbel/aws.json
rm ./b/babbel/github.json
rm ./b/bd-spl/helm.json
rm ./b/benesch/postgresql.json
rm ./b/bartoszj/kong.json
rm ./b/bartoszj/instaclustr.json
rm ./b/bishtawi/auth0.json
rm ./b/brightbox/brightbox-old.json
rm ./b/Brightspace/okta.json
rm ./k/kevinbuckley/snowflake.json
rm ./k/kei-q/papertrail.json
rm ./k/kontena/kontena.json
rm ./l/lsst-sqre/influxdb.json
rm ./l/lpxavi/phpipam.json
rm ./l/limkin092/cassandra.json
rm ./l/lippertmarkus/vagrant.json
rm ./l/lemon-li/jenkins.json
rm ./2/23doors/aws.json
rm ./2/23doors/spinnaker.json
rm ./y/yurymkomarov/redshift.json
rm ./y/yoyolabsio/kafka-connect.json
rm ./p/packetloop/kafka.json
rm ./p/pcharl29/netapp-gcp.json
rm ./p/psychz-networks/psychz.json
rm ./p/petern-sc/confluentcloud.json
rm ./p/PatrickDelancy/solace.json
rm ./p/paybyphone/phpipam.json
rm ./p/PMI-DEEP-Infra/appstream-v2.json
rm ./w/Worldremit/confluentcloud.json
rm ./w/WhistleLabs/cloudamqp.json
rm ./w/WhistleLabs/logentries.json
rm ./w/WhistleLabs/nrs.json
rm ./w/WhistleLabs/rabbitmq.json
rm ./w/WhistleLabs/sentry.json
rm ./w/WhistleLabs/pagerduty.json
rm ./w/WhistleLabs/aws.json
rm ./w/WhistleLabs/datadog.json
rm ./w/WhistleLabs/atlas.json
rm ./w/WhistleLabs/heroku.json
rm ./w/wizzie-io/kubernetes.json
rm ./w/wbat/github-bak.json
rm ./w/wernerstrydom/netbox-old.json
